
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
    - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
    - wordpress_data:/var/www/html
    depends_on:
    - wordpress
    networks:
    - inception_net
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      DOMAIN: ${DOMAIN}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_net
    restart: unless-stopped
    
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_net
    restart: unless-stopped
    
networks:
  inception_net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
