FROM alpine:3.20

RUN apk add --no-cache \
    php82 \
    php82-fpm \
    php82-mysqli \
    php82-curl \
    php82-dom \
    php82-exif \
    php82-fileinfo \
    php82-pecl-igbinary \
    php82-openssl \
    php82-mbstring \
    php82-json \
    php82-xml \
    php82-session \
    php82-tokenizer \
    php82-gd \
    php82-zip \
    php82-phar \
    php82-iconv \
    php82-shmop \
    php82-cli \
    mysql-client \
    php82-simplexml \
    php82-sodium \
    mariadb-client \
    bash \
    curl \
    nano \
    openssl \
    net-tools \
    inetutils-telnet \
    iputils \
    && rm -rf /var/cache/apk/*

RUN curl -L -O https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php && \
	mkdir -p /var/www/html && \
	mv ./adminer-4.8.1.php /var/www/html/index.php && \
	adduser -u 82 -D -S -G www-data www-data

RUN sed -i 's/^listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/' /etc/php82/php-fpm.d/www.conf

EXPOSE 9000

CMD ["php-fpm82", "-F"]
